"""
Physics Configuration Asset Generator

Reads PhysicsConfigs.json and generates Unreal Python scripts to create Data Assets.
Can be run in Unreal Editor's Python console or via command line.

Usage:
    1. In Unreal Editor Python console:
        exec(open('generate_physics_assets.py').read())

    2. From command line:
        UnrealEditor.exe YourProject.uproject -ExecutePythonScript="generate_physics_assets.py"
"""

import json
import os
import sys
from pathlib import Path

# Configuration
PROJECT_ROOT = Path(__file__).parent
PHYSICS_JSON = PROJECT_ROOT / "Content" / "Data" / "PhysicsConfigs.json"
OUTPUT_PATH = "/Game/Data/PhysicsConfigs"  # Content Browser path
SCRIPT_OUTPUT = PROJECT_ROOT / "generated_create_physics_assets.py"

def load_physics_configs():
    """Load physics configurations from JSON file"""
    if not PHYSICS_JSON.exists():
        print(f"ERROR: Physics config JSON not found at {PHYSICS_JSON}")
        return None

    with open(PHYSICS_JSON, 'r') as f:
        data = json.load(f)

    return data.get('configs', [])

def sanitize_asset_name(config_name):
    """Convert config name to valid asset name"""
    # Remove spaces and special characters
    asset_name = config_name.replace(" ", "")
    # Add DA_ prefix
    return f"DA_{asset_name}"

def generate_unreal_python_script(configs):
    """Generate Unreal Python script to create all data assets"""

    script = """
# Auto-generated script to create Ship Physics Config Data Assets
# Generated by generate_physics_assets.py

import unreal

# Asset paths
output_path = "/Game/Data/PhysicsConfigs"

# Ensure output directory exists
asset_tools = unreal.AssetToolsHelpers.get_asset_tools()

print("Creating Ship Physics Config Data Assets...")
print(f"Output path: {output_path}")

configs_created = []

"""

    for config in configs:
        asset_name = sanitize_asset_name(config['ConfigName'])

        script += f"""
# ============================================================
# {config['ConfigName']}
# ============================================================
print("Creating {asset_name}...")

# Create the data asset
package_name = f"{{output_path}}/{asset_name}"
asset_factory = unreal.ShipPhysicsConfigFactory()  # You may need a custom factory
new_asset = asset_tools.create_asset(
    asset_name="{asset_name}",
    package_path=output_path,
    asset_class=unreal.ShipPhysicsConfig,
    factory=unreal.DataAssetFactory()
)

if new_asset:
    # Set configuration name and description
    new_asset.set_editor_property("config_name", unreal.Text("{config['ConfigName']}"))
    new_asset.set_editor_property("description", unreal.Text("{config['Description']}"))

    # Set physics parameters
    new_asset.set_editor_property("mass", {config['Mass']})
    new_asset.set_editor_property("thrust_power", {config['ThrustPower']})
    new_asset.set_editor_property("max_velocity", {config['MaxVelocity']})
    new_asset.set_editor_property("angular_thrust_power", {config['AngularThrustPower']})
    new_asset.set_editor_property("fuel_capacity", {config['FuelCapacity']})
    new_asset.set_editor_property("fuel_consumption_rate", {config['FuelConsumptionRate']})

    # Set flight characteristics
    new_asset.set_editor_property("acceleration_multiplier", {config['AccelerationMultiplier']})
    new_asset.set_editor_property("rotation_speed_multiplier", {config['RotationSpeedMultiplier']})
    new_asset.set_editor_property("stability_assist_strength", {config['StabilityAssistStrength']})

    # Save the asset
    unreal.EditorAssetLibrary.save_asset(new_asset.get_path_name())

    print(f"  ✓ Created: {asset_name}")
    configs_created.append("{asset_name}")
else:
    print(f"  ✗ Failed to create: {asset_name}")

"""

    script += """
# ============================================================
# Summary
# ============================================================
print("\\n" + "="*60)
print(f"Physics Config Asset Creation Complete!")
print(f"Created {len(configs_created)} / """ + str(len(configs)) + """ assets")
print("="*60)

for asset in configs_created:
    print(f"  ✓ {asset}")

print("\\nAssets saved to:", output_path)
print("You can now use these configs in your ship customization system!")
"""

    return script

def generate_manual_instructions(configs):
    """Generate manual step-by-step instructions for creating assets in Unreal"""

    instructions = """
# Manual Data Asset Creation Instructions

If the automated Python script doesn't work, follow these manual steps:

## Step 1: Create Output Folder
1. In Content Browser, navigate to Content/Data
2. Right-click > New Folder > Name it "PhysicsConfigs"

## Step 2: Create Each Data Asset

For each configuration below, do the following:

1. Right-click in Content/Data/PhysicsConfigs
2. Select Miscellaneous > Data Asset
3. Choose "ShipPhysicsConfig" as the type
4. Name it as specified below
5. Double-click to open and set the values

---

"""

    for i, config in enumerate(configs, 1):
        asset_name = sanitize_asset_name(config['ConfigName'])

        instructions += f"""
## Config {i}/{len(configs)}: {config['ConfigName']}

**Asset Name**: `{asset_name}`

### Config Settings:
- Config Name: {config['ConfigName']}
- Description: {config['Description']}

### Physics Parameters:
- Mass: {config['Mass']} kg
- Thrust Power: {config['ThrustPower']} N
- Max Velocity: {config['MaxVelocity']} m/s
- Angular Thrust Power: {config['AngularThrustPower']} N
- Fuel Capacity: {config['FuelCapacity']}
- Fuel Consumption Rate: {config['FuelConsumptionRate']}

### Flight Characteristics:
- Acceleration Multiplier: {config['AccelerationMultiplier']}
- Rotation Speed Multiplier: {config['RotationSpeedMultiplier']}
- Stability Assist Strength: {config['StabilityAssistStrength']}

**Notes**: {config.get('Notes', 'N/A')}

---

"""

    return instructions

def generate_batch_import_commands(configs):
    """Generate batch commands for asset creation"""

    commands = """# Batch Import Commands
# Copy and paste these into Unreal Editor's Output Log (or Python console)

"""

    for config in configs:
        asset_name = sanitize_asset_name(config['ConfigName'])
        commands += f"""
# {config['ConfigName']}
unreal.AssetToolsHelpers.get_asset_tools().create_asset("{asset_name}", "{OUTPUT_PATH}", unreal.ShipPhysicsConfig, unreal.DataAssetFactory())
"""

    return commands

def main():
    """Main execution"""
    print("="*60)
    print("Physics Configuration Asset Generator")
    print("="*60)

    # Load configs
    configs = load_physics_configs()
    if not configs:
        print("ERROR: No configurations loaded. Exiting.")
        return 1

    print(f"\nLoaded {len(configs)} physics configurations:")
    for config in configs:
        print(f"  - {config['ConfigName']}")

    # Generate Unreal Python script
    print(f"\nGenerating Unreal Python script...")
    unreal_script = generate_unreal_python_script(configs)

    script_path = PROJECT_ROOT / "generated_create_physics_assets.py"
    with open(script_path, 'w', encoding='utf-8') as f:
        f.write(unreal_script)
    print(f"  [OK] Saved to: {script_path}")

    # Generate manual instructions
    print(f"\nGenerating manual instructions...")
    instructions = generate_manual_instructions(configs)

    instructions_path = PROJECT_ROOT / "MANUAL_PHYSICS_ASSET_CREATION.md"
    with open(instructions_path, 'w', encoding='utf-8') as f:
        f.write(instructions)
    print(f"  [OK] Saved to: {instructions_path}")

    # Generate batch commands
    print(f"\nGenerating batch import commands...")
    batch_commands = generate_batch_import_commands(configs)

    batch_path = PROJECT_ROOT / "batch_import_physics_assets.txt"
    with open(batch_path, 'w', encoding='utf-8') as f:
        f.write(batch_commands)
    print(f"  [OK] Saved to: {batch_path}")

    print("\n" + "="*60)
    print("Generation Complete!")
    print("="*60)
    print("\nNext Steps:")
    print("1. Open Unreal Editor")
    print("2. Open Python console (Window > Developer Tools > Python Console)")
    print("3. Run: exec(open('generated_create_physics_assets.py').read())")
    print("\nOR manually create assets using: MANUAL_PHYSICS_ASSET_CREATION.md")
    print("="*60)

    return 0

if __name__ == "__main__":
    sys.exit(main())
