
# Auto-generated script to create Ship Physics Config Data Assets
# Generated by generate_physics_assets.py

import unreal

# Asset paths
output_path = "/Game/Data/PhysicsConfigs"

# Ensure output directory exists
asset_tools = unreal.AssetToolsHelpers.get_asset_tools()

print("Creating Ship Physics Config Data Assets...")
print(f"Output path: {output_path}")

configs_created = []


# ============================================================
# Light Fighter
# ============================================================
print("Creating DA_LightFighter...")

# Create the data asset
package_name = f"{output_path}/DA_LightFighter"
asset_factory = unreal.ShipPhysicsConfigFactory()  # You may need a custom factory
new_asset = asset_tools.create_asset(
    asset_name="DA_LightFighter",
    package_path=output_path,
    asset_class=unreal.ShipPhysicsConfig,
    factory=unreal.DataAssetFactory()
)

if new_asset:
    # Set configuration name and description
    new_asset.set_editor_property("config_name", unreal.Text("Light Fighter"))
    new_asset.set_editor_property("description", unreal.Text("Fast and agile combat ship with excellent maneuverability"))

    # Set physics parameters
    new_asset.set_editor_property("mass", 500.0)
    new_asset.set_editor_property("thrust_power", 150000.0)
    new_asset.set_editor_property("max_velocity", 1500.0)
    new_asset.set_editor_property("angular_thrust_power", 75000.0)
    new_asset.set_editor_property("fuel_capacity", 800.0)
    new_asset.set_editor_property("fuel_consumption_rate", 1.2)

    # Set flight characteristics
    new_asset.set_editor_property("acceleration_multiplier", 1.5)
    new_asset.set_editor_property("rotation_speed_multiplier", 1.3)
    new_asset.set_editor_property("stability_assist_strength", 0.4)

    # Save the asset
    unreal.EditorAssetLibrary.save_asset(new_asset.get_path_name())

    print(f"  ✓ Created: DA_LightFighter")
    configs_created.append("DA_LightFighter")
else:
    print(f"  ✗ Failed to create: DA_LightFighter")


# ============================================================
# Heavy Freighter
# ============================================================
print("Creating DA_HeavyFreighter...")

# Create the data asset
package_name = f"{output_path}/DA_HeavyFreighter"
asset_factory = unreal.ShipPhysicsConfigFactory()  # You may need a custom factory
new_asset = asset_tools.create_asset(
    asset_name="DA_HeavyFreighter",
    package_path=output_path,
    asset_class=unreal.ShipPhysicsConfig,
    factory=unreal.DataAssetFactory()
)

if new_asset:
    # Set configuration name and description
    new_asset.set_editor_property("config_name", unreal.Text("Heavy Freighter"))
    new_asset.set_editor_property("description", unreal.Text("Massive cargo hauler with powerful thrust and high stability"))

    # Set physics parameters
    new_asset.set_editor_property("mass", 3000.0)
    new_asset.set_editor_property("thrust_power", 200000.0)
    new_asset.set_editor_property("max_velocity", 600.0)
    new_asset.set_editor_property("angular_thrust_power", 60000.0)
    new_asset.set_editor_property("fuel_capacity", 2000.0)
    new_asset.set_editor_property("fuel_consumption_rate", 2.5)

    # Set flight characteristics
    new_asset.set_editor_property("acceleration_multiplier", 0.6)
    new_asset.set_editor_property("rotation_speed_multiplier", 0.5)
    new_asset.set_editor_property("stability_assist_strength", 0.8)

    # Save the asset
    unreal.EditorAssetLibrary.save_asset(new_asset.get_path_name())

    print(f"  ✓ Created: DA_HeavyFreighter")
    configs_created.append("DA_HeavyFreighter")
else:
    print(f"  ✗ Failed to create: DA_HeavyFreighter")


# ============================================================
# Balanced Scout
# ============================================================
print("Creating DA_BalancedScout...")

# Create the data asset
package_name = f"{output_path}/DA_BalancedScout"
asset_factory = unreal.ShipPhysicsConfigFactory()  # You may need a custom factory
new_asset = asset_tools.create_asset(
    asset_name="DA_BalancedScout",
    package_path=output_path,
    asset_class=unreal.ShipPhysicsConfig,
    factory=unreal.DataAssetFactory()
)

if new_asset:
    # Set configuration name and description
    new_asset.set_editor_property("config_name", unreal.Text("Balanced Scout"))
    new_asset.set_editor_property("description", unreal.Text("Well-rounded ship suitable for all mission types"))

    # Set physics parameters
    new_asset.set_editor_property("mass", 1000.0)
    new_asset.set_editor_property("thrust_power", 120000.0)
    new_asset.set_editor_property("max_velocity", 1000.0)
    new_asset.set_editor_property("angular_thrust_power", 60000.0)
    new_asset.set_editor_property("fuel_capacity", 1200.0)
    new_asset.set_editor_property("fuel_consumption_rate", 1.5)

    # Set flight characteristics
    new_asset.set_editor_property("acceleration_multiplier", 1.0)
    new_asset.set_editor_property("rotation_speed_multiplier", 1.0)
    new_asset.set_editor_property("stability_assist_strength", 0.5)

    # Save the asset
    unreal.EditorAssetLibrary.save_asset(new_asset.get_path_name())

    print(f"  ✓ Created: DA_BalancedScout")
    configs_created.append("DA_BalancedScout")
else:
    print(f"  ✗ Failed to create: DA_BalancedScout")


# ============================================================
# Speed Demon
# ============================================================
print("Creating DA_SpeedDemon...")

# Create the data asset
package_name = f"{output_path}/DA_SpeedDemon"
asset_factory = unreal.ShipPhysicsConfigFactory()  # You may need a custom factory
new_asset = asset_tools.create_asset(
    asset_name="DA_SpeedDemon",
    package_path=output_path,
    asset_class=unreal.ShipPhysicsConfig,
    factory=unreal.DataAssetFactory()
)

if new_asset:
    # Set configuration name and description
    new_asset.set_editor_property("config_name", unreal.Text("Speed Demon"))
    new_asset.set_editor_property("description", unreal.Text("Maximum velocity racing ship with minimal flight assistance"))

    # Set physics parameters
    new_asset.set_editor_property("mass", 350.0)
    new_asset.set_editor_property("thrust_power", 180000.0)
    new_asset.set_editor_property("max_velocity", 2000.0)
    new_asset.set_editor_property("angular_thrust_power", 50000.0)
    new_asset.set_editor_property("fuel_capacity", 600.0)
    new_asset.set_editor_property("fuel_consumption_rate", 2.0)

    # Set flight characteristics
    new_asset.set_editor_property("acceleration_multiplier", 2.0)
    new_asset.set_editor_property("rotation_speed_multiplier", 0.9)
    new_asset.set_editor_property("stability_assist_strength", 0.2)

    # Save the asset
    unreal.EditorAssetLibrary.save_asset(new_asset.get_path_name())

    print(f"  ✓ Created: DA_SpeedDemon")
    configs_created.append("DA_SpeedDemon")
else:
    print(f"  ✗ Failed to create: DA_SpeedDemon")


# ============================================================
# Juggernaut
# ============================================================
print("Creating DA_Juggernaut...")

# Create the data asset
package_name = f"{output_path}/DA_Juggernaut"
asset_factory = unreal.ShipPhysicsConfigFactory()  # You may need a custom factory
new_asset = asset_tools.create_asset(
    asset_name="DA_Juggernaut",
    package_path=output_path,
    asset_class=unreal.ShipPhysicsConfig,
    factory=unreal.DataAssetFactory()
)

if new_asset:
    # Set configuration name and description
    new_asset.set_editor_property("config_name", unreal.Text("Juggernaut"))
    new_asset.set_editor_property("description", unreal.Text("Heavily armored assault ship with devastating firepower"))

    # Set physics parameters
    new_asset.set_editor_property("mass", 4000.0)
    new_asset.set_editor_property("thrust_power", 300000.0)
    new_asset.set_editor_property("max_velocity", 400.0)
    new_asset.set_editor_property("angular_thrust_power", 120000.0)
    new_asset.set_editor_property("fuel_capacity", 2500.0)
    new_asset.set_editor_property("fuel_consumption_rate", 3.5)

    # Set flight characteristics
    new_asset.set_editor_property("acceleration_multiplier", 0.4)
    new_asset.set_editor_property("rotation_speed_multiplier", 0.4)
    new_asset.set_editor_property("stability_assist_strength", 0.9)

    # Save the asset
    unreal.EditorAssetLibrary.save_asset(new_asset.get_path_name())

    print(f"  ✓ Created: DA_Juggernaut")
    configs_created.append("DA_Juggernaut")
else:
    print(f"  ✗ Failed to create: DA_Juggernaut")


# ============================================================
# Interceptor
# ============================================================
print("Creating DA_Interceptor...")

# Create the data asset
package_name = f"{output_path}/DA_Interceptor"
asset_factory = unreal.ShipPhysicsConfigFactory()  # You may need a custom factory
new_asset = asset_tools.create_asset(
    asset_name="DA_Interceptor",
    package_path=output_path,
    asset_class=unreal.ShipPhysicsConfig,
    factory=unreal.DataAssetFactory()
)

if new_asset:
    # Set configuration name and description
    new_asset.set_editor_property("config_name", unreal.Text("Interceptor"))
    new_asset.set_editor_property("description", unreal.Text("Fast-response combat ship designed for pursuit missions"))

    # Set physics parameters
    new_asset.set_editor_property("mass", 600.0)
    new_asset.set_editor_property("thrust_power", 140000.0)
    new_asset.set_editor_property("max_velocity", 1400.0)
    new_asset.set_editor_property("angular_thrust_power", 70000.0)
    new_asset.set_editor_property("fuel_capacity", 900.0)
    new_asset.set_editor_property("fuel_consumption_rate", 1.3)

    # Set flight characteristics
    new_asset.set_editor_property("acceleration_multiplier", 1.4)
    new_asset.set_editor_property("rotation_speed_multiplier", 1.4)
    new_asset.set_editor_property("stability_assist_strength", 0.3)

    # Save the asset
    unreal.EditorAssetLibrary.save_asset(new_asset.get_path_name())

    print(f"  ✓ Created: DA_Interceptor")
    configs_created.append("DA_Interceptor")
else:
    print(f"  ✗ Failed to create: DA_Interceptor")


# ============================================================
# Stealth Scout
# ============================================================
print("Creating DA_StealthScout...")

# Create the data asset
package_name = f"{output_path}/DA_StealthScout"
asset_factory = unreal.ShipPhysicsConfigFactory()  # You may need a custom factory
new_asset = asset_tools.create_asset(
    asset_name="DA_StealthScout",
    package_path=output_path,
    asset_class=unreal.ShipPhysicsConfig,
    factory=unreal.DataAssetFactory()
)

if new_asset:
    # Set configuration name and description
    new_asset.set_editor_property("config_name", unreal.Text("Stealth Scout"))
    new_asset.set_editor_property("description", unreal.Text("Reconnaissance ship with low signature and precise handling"))

    # Set physics parameters
    new_asset.set_editor_property("mass", 700.0)
    new_asset.set_editor_property("thrust_power", 100000.0)
    new_asset.set_editor_property("max_velocity", 1200.0)
    new_asset.set_editor_property("angular_thrust_power", 55000.0)
    new_asset.set_editor_property("fuel_capacity", 1000.0)
    new_asset.set_editor_property("fuel_consumption_rate", 1.1)

    # Set flight characteristics
    new_asset.set_editor_property("acceleration_multiplier", 1.1)
    new_asset.set_editor_property("rotation_speed_multiplier", 1.2)
    new_asset.set_editor_property("stability_assist_strength", 0.6)

    # Save the asset
    unreal.EditorAssetLibrary.save_asset(new_asset.get_path_name())

    print(f"  ✓ Created: DA_StealthScout")
    configs_created.append("DA_StealthScout")
else:
    print(f"  ✗ Failed to create: DA_StealthScout")


# ============================================================
# Assault Bomber
# ============================================================
print("Creating DA_AssaultBomber...")

# Create the data asset
package_name = f"{output_path}/DA_AssaultBomber"
asset_factory = unreal.ShipPhysicsConfigFactory()  # You may need a custom factory
new_asset = asset_tools.create_asset(
    asset_name="DA_AssaultBomber",
    package_path=output_path,
    asset_class=unreal.ShipPhysicsConfig,
    factory=unreal.DataAssetFactory()
)

if new_asset:
    # Set configuration name and description
    new_asset.set_editor_property("config_name", unreal.Text("Assault Bomber"))
    new_asset.set_editor_property("description", unreal.Text("Heavy weapons platform designed for anti-capital ship combat"))

    # Set physics parameters
    new_asset.set_editor_property("mass", 2500.0)
    new_asset.set_editor_property("thrust_power", 180000.0)
    new_asset.set_editor_property("max_velocity", 700.0)
    new_asset.set_editor_property("angular_thrust_power", 80000.0)
    new_asset.set_editor_property("fuel_capacity", 1800.0)
    new_asset.set_editor_property("fuel_consumption_rate", 2.2)

    # Set flight characteristics
    new_asset.set_editor_property("acceleration_multiplier", 0.7)
    new_asset.set_editor_property("rotation_speed_multiplier", 0.6)
    new_asset.set_editor_property("stability_assist_strength", 0.7)

    # Save the asset
    unreal.EditorAssetLibrary.save_asset(new_asset.get_path_name())

    print(f"  ✓ Created: DA_AssaultBomber")
    configs_created.append("DA_AssaultBomber")
else:
    print(f"  ✗ Failed to create: DA_AssaultBomber")


# ============================================================
# Civilian Shuttle
# ============================================================
print("Creating DA_CivilianShuttle...")

# Create the data asset
package_name = f"{output_path}/DA_CivilianShuttle"
asset_factory = unreal.ShipPhysicsConfigFactory()  # You may need a custom factory
new_asset = asset_tools.create_asset(
    asset_name="DA_CivilianShuttle",
    package_path=output_path,
    asset_class=unreal.ShipPhysicsConfig,
    factory=unreal.DataAssetFactory()
)

if new_asset:
    # Set configuration name and description
    new_asset.set_editor_property("config_name", unreal.Text("Civilian Shuttle"))
    new_asset.set_editor_property("description", unreal.Text("Safe and stable passenger transport with maximum comfort"))

    # Set physics parameters
    new_asset.set_editor_property("mass", 1500.0)
    new_asset.set_editor_property("thrust_power", 110000.0)
    new_asset.set_editor_property("max_velocity", 800.0)
    new_asset.set_editor_property("angular_thrust_power", 50000.0)
    new_asset.set_editor_property("fuel_capacity", 1400.0)
    new_asset.set_editor_property("fuel_consumption_rate", 1.6)

    # Set flight characteristics
    new_asset.set_editor_property("acceleration_multiplier", 0.8)
    new_asset.set_editor_property("rotation_speed_multiplier", 0.8)
    new_asset.set_editor_property("stability_assist_strength", 0.9)

    # Save the asset
    unreal.EditorAssetLibrary.save_asset(new_asset.get_path_name())

    print(f"  ✓ Created: DA_CivilianShuttle")
    configs_created.append("DA_CivilianShuttle")
else:
    print(f"  ✗ Failed to create: DA_CivilianShuttle")


# ============================================================
# Support Ship
# ============================================================
print("Creating DA_SupportShip...")

# Create the data asset
package_name = f"{output_path}/DA_SupportShip"
asset_factory = unreal.ShipPhysicsConfigFactory()  # You may need a custom factory
new_asset = asset_tools.create_asset(
    asset_name="DA_SupportShip",
    package_path=output_path,
    asset_class=unreal.ShipPhysicsConfig,
    factory=unreal.DataAssetFactory()
)

if new_asset:
    # Set configuration name and description
    new_asset.set_editor_property("config_name", unreal.Text("Support Ship"))
    new_asset.set_editor_property("description", unreal.Text("Reliable utility workhorse for repair and resupply missions"))

    # Set physics parameters
    new_asset.set_editor_property("mass", 1800.0)
    new_asset.set_editor_property("thrust_power", 130000.0)
    new_asset.set_editor_property("max_velocity", 900.0)
    new_asset.set_editor_property("angular_thrust_power", 65000.0)
    new_asset.set_editor_property("fuel_capacity", 1600.0)
    new_asset.set_editor_property("fuel_consumption_rate", 1.8)

    # Set flight characteristics
    new_asset.set_editor_property("acceleration_multiplier", 0.9)
    new_asset.set_editor_property("rotation_speed_multiplier", 0.9)
    new_asset.set_editor_property("stability_assist_strength", 0.8)

    # Save the asset
    unreal.EditorAssetLibrary.save_asset(new_asset.get_path_name())

    print(f"  ✓ Created: DA_SupportShip")
    configs_created.append("DA_SupportShip")
else:
    print(f"  ✗ Failed to create: DA_SupportShip")


# ============================================================
# Summary
# ============================================================
print("\n" + "="*60)
print(f"Physics Config Asset Creation Complete!")
print(f"Created {len(configs_created)} / 10 assets")
print("="*60)

for asset in configs_created:
    print(f"  ✓ {asset}")

print("\nAssets saved to:", output_path)
print("You can now use these configs in your ship customization system!")
