"""
Continuous Visual Development Loop
I (the AI) continuously improve the cockpit based on what I see
"""

import unreal
import json
import urllib.request
import base64
import time
import os

print("\n" + "="*70)
print("  🔄 CONTINUOUS VISUAL DEVELOPMENT LOOP")
print("="*70 + "\n")

# Subsystems
editor_asset_lib = unreal.EditorAssetLibrary()
editor_level_lib = unreal.EditorLevelLibrary()
asset_tools = unreal.AssetToolsHelpers.get_asset_tools()

AI_BACKEND_URL = "http://localhost:8000/analyze-and-develop"
PROJECT_DIR = unreal.SystemLibrary.get_project_directory()
ITERATION_DELAY = 30  # seconds between iterations

iteration_count = 0
max_iterations = 5  # Limit iterations to prevent infinite loop

def take_screenshot_simple():
    """Take a screenshot using Unreal's built-in system"""
    print("📸 Taking screenshot...")
    
    try:
        # Use high-res screenshot
        unreal.AutomationLibrary.take_high_res_screenshot(1920, 1080, f"iteration_{iteration_count}.png")
        
        # Wait for file to be written
        time.sleep(2)
        
        # Find the screenshot
        screenshot_dir = os.path.join(PROJECT_DIR, "Saved", "Screenshots", "Windows")
        if os.path.exists(screenshot_dir):
            screenshots = [f for f in os.listdir(screenshot_dir) if f.endswith('.png')]
            if screenshots:
                latest = max(screenshots, key=lambda f: os.path.getmtime(os.path.join(screenshot_dir, f)))
                screenshot_path = os.path.join(screenshot_dir, latest)
                print(f"  ✅ Screenshot: {screenshot_path}")
                return screenshot_path
        
        print("  ⚠ Screenshot file not found")
        return None
        
    except Exception as e:
        print(f"  ❌ Screenshot error: {e}")
        return None

def get_scene_info():
    """Get information about what's currently in the scene"""
    actors = editor_level_lib.get_all_level_actors()
    spaceship_actors = [a for a in actors if a and "SpaceShip" in str(a.get_class().get_name()) or "BP_" in str(a.get_actor_label())]
    
    scene_info = {
        "total_actors": len(actors),
        "spaceship_actors": len(spaceship_actors),
        "actor_names": [str(a.get_actor_label()) for a in spaceship_actors if a]
    }
    
    return scene_info

def analyze_with_ai(screenshot_path, scene_info):
    """Send screenshot to AI for analysis"""
    print(f"\n🤖 AI analyzing iteration {iteration_count}...")
    
    if not screenshot_path or not os.path.exists(screenshot_path):
        print("  ⚠ No screenshot to analyze")
        return None
    
    try:
        # Read and encode screenshot
        with open(screenshot_path, 'rb') as f:
            image_data = base64.b64encode(f.read()).decode('utf-8')
        
        # Build context
        context = f"""
Iteration {iteration_count} of VR spaceship cockpit development.

Current scene:
- Total actors: {scene_info['total_actors']}
- Spaceship components: {scene_info['spaceship_actors']}
- Components in scene: {', '.join(scene_info['actor_names'])}

Analyze the screenshot and suggest improvements:
1. Are the cockpit components visible?
2. Are they positioned correctly for VR?
3. Do they need better spacing or rotation?
4. What should be added or adjusted next?

Provide specific Python code using unreal module to make improvements.
"""
        
        # Prepare request
        data = {
            "image": image_data,
            "context": context,
            "goal": "Build immersive VR spaceship cockpit with proper spatial layout"
        }
        
        # Send to backend
        req = urllib.request.Request(
            AI_BACKEND_URL,
            data=json.dumps(data).encode('utf-8'),
            headers={'Content-Type': 'application/json'}
        )
        
        with urllib.request.urlopen(req, timeout=30) as response:
            result = json.loads(response.read().decode('utf-8'))
            
            print(f"  ✅ AI Analysis complete!")
            print(f"\n  💭 {result.get('analysis', 'No analysis')}\n")
            
            return result
            
    except urllib.error.URLError as e:
        print(f"  ⚠ Backend not responding: {e}")
        print("  💡 Start backend: cd ai_backend && python main.py")
        return None
    except Exception as e:
        print(f"  ❌ Error: {e}")
        return None

def execute_ai_code(ai_result):
    """Execute Python code generated by AI"""
    if not ai_result:
        return False
    
    code = ai_result.get('code', '')
    if not code:
        print("  ℹ️  No code to execute")
        return False
    
    print("\n⚙️  Executing AI-generated improvements...")
    print(f"```python\n{code}\n```\n")
    
    try:
        exec(code, globals())
        print("  ✅ Code executed successfully")
        return True
    except Exception as e:
        print(f"  ❌ Execution error: {e}")
        import traceback
        traceback.print_exc()
        return False

def continuous_development_loop():
    """Main loop: Screenshot → Analyze → Improve → Repeat"""
    global iteration_count
    
    print("🚀 Starting continuous development loop...")
    print(f"   Max iterations: {max_iterations}")
    print(f"   Delay between iterations: {ITERATION_DELAY}s\n")
    
    while iteration_count < max_iterations:
        iteration_count += 1
        
        print("=" * 70)
        print(f"  ITERATION {iteration_count}/{max_iterations}")
        print("=" * 70 + "\n")
        
        # Get current scene state
        scene_info = get_scene_info()
        print(f"📊 Scene: {scene_info['spaceship_actors']} spaceship actors")
        
        # Take screenshot
        screenshot_path = take_screenshot_simple()
        
        if screenshot_path:
            # Analyze with AI
            ai_result = analyze_with_ai(screenshot_path, scene_info)
            
            if ai_result:
                # Execute improvements
                success = execute_ai_code(ai_result)
                
                if success:
                    print(f"\n✅ Iteration {iteration_count} complete - improvements applied")
                else:
                    print(f"\n⚠ Iteration {iteration_count} complete - no changes made")
            else:
                print(f"\n⚠ Iteration {iteration_count}: AI backend not available")
                print("   Continuing without AI feedback...")
        else:
            print(f"\n⚠ Iteration {iteration_count}: Screenshot failed")
        
        # Wait before next iteration (unless it's the last one)
        if iteration_count < max_iterations:
            print(f"\n⏳ Waiting {ITERATION_DELAY}s before next iteration...")
            time.sleep(ITERATION_DELAY)
    
    print("\n" + "=" * 70)
    print(f"  🎉 COMPLETED {max_iterations} ITERATIONS!")
    print("=" * 70)
    print("\n💡 Check the viewport to see the evolved cockpit design!")
    print("💡 Review screenshots in: Saved/Screenshots/Windows/\n")

# Start the loop
if __name__ == "__main__":
    continuous_development_loop()
